name: 01 - Building Blocks
on: push # trigger

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World!"

  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "i will succeed"
          exit 0
      - name: say goodvye
        run: echo "GoodBye!"
  
