name: 01 - Building Blocks
on: push # trigger

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World!"

  echo-bye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "job failed"
          exit 1
      - name: say goodvye
        run: echo "GoodBye!"
  
