name: 02 - Workflow Events
on: 
    # pull_request:       # a pull_request event
    workflow_dispatch:  # a workflow_dispatch event, other examples of events:- push, schedule, workflow_call etc.

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "I've been triggered by event ${{github.event_name}}."
              
