name: 03 - Workflow Runners
on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest # this is a runner, a runner is a VM on which jobs run.
        steps:
            - name: show_os
              run: |
                echo "This job is running on an ubuntu runner"
                echo "Runner OS: $RUNNER_OS"

    windows-echo:
        runs-on: windows-latest
        steps:
            - name: show_os
              shell: bash # we have to use this beacuse by default windows won't show OS using $RUNNER_OS, we have to explicitly define the shell type.
              run: |
                echo "This job is running on a windows runner"
                echo "Runner OS: $RUNNER_OS"

    mac-echo:
        runs-on: macos-latest
        steps:
            - name: show_os
              run: |
                echo "This job is running on an macos runner"
                echo "Runner OS: $RUNNER_OS"
            