name: 06 - Contexts
on:
    # push:
    workflow_dispatch:
        inputs:
            debug:
                required: true
                type: boolean
                default: false

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        env:
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Run number: ${{github.run_number}}"
            - name: Retrieve Variable
              env:
                MY_VAR: "hello world"
              run: |
                echo "repository variable : $MY_VAR"
            - name: Retrieve Variable from Variables stored in Github UI
              run: |
                echo "This variable value is comming from github UI, variable value : ${{vars.MY_VAR_UI}}"
            - name: Print Env Variables
              env:
                MY_OVERWRITTEN_VAR: "step"
              run: |                                                
                echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"        
            - name: Print Env Variables
              run: |
                echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"

# If Same Variable is defined at step, job and workflow level, then 1] step variable will take precedence over job variables
# 2] job variable will take precedence over wrokflow variable. 