## Single Workflow -
## Multiple Workflows -
    
    ## Variable can be fetched in a single workflow using "env" context.
    ## In a Multiple workflows scenario variables can be fetched using "vars" context.

    ## Single workflow variables are set at levels:- workflow, jobs and steps
        # If same variables are defined at workflow, job and step level, then Step variables will take precedence over Job variables
        # and Job variables will take precedence over workflow variables.  

    ## Multiple Workflows variables are set at levels: Organization, Repository and Environment.

name: 08 - Using Variables
on:
    # push:
    workflow_dispatch:

env:
    WORKFLOW_VAR: 'I am a workflow environment variable'
    OVERWRITTEN: 'I will be overwritten'
    UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default undefined value' }}

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            JOB_VAR: 'I am a job env variable'
            OVERWRITTEN: 'I have been overwritten at the job level'
        steps:
            - name: Print Env Variable
              env:
                STEP_VAR: 'I am a step env var'
                step_var2: 'I am another step var'
              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"
                echo "Step env var 2: ${{ env.step_var2 }}"
                echo "Job env var: ${{ env.JOB_VAR }}"
                echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten: ${{ env.OVERWRITTEN }}"

            - name: Overwrite Job Variable
              env:
                OVERWRITTEN: 'I have been overwritten at the step level'
              run: |
                echo "Step env var: ${{ env.OVERWRITTEN }}"

## Begin - Multiple Workflows Variables use case - context "vars".
    echo2:
        runs-on: ubuntu-latest
        steps:
            - name: Print Variables
              run: |
                echo "Repository Variable: ${{ vars.REPOSITORY_VAR }}"
                
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Print Prod Env Variables
              run: |
                echo "Repository Variable: ${{ vars.REPOSITORY_VAR }}"
                echo "Environment Variable: ${{ vars.TARGET_VAR }}"
                echo "Overwritten Variable: ${{ vars.OVERWRITTEN_VAR }}"

    echo-staging:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Print Prod Env Variables
              run: |
                echo "Repository Variable: ${{ vars.REPOSITORY_VAR }}"
                echo "Environment Variable: ${{ vars.TARGET_VAR }}"

    echo-undefined:
        runs-on: ubuntu-latest
        steps:
            - name: Print undefined Variables
              run: |
                echo "Github Organization Variable: ${{ env.UNDEFINED_VAR_WITH_DEFAULT }}"
