name: 09 - Using Functions
on:
    # pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            # - name: Print PR title                                    # commented three steps, because we don't need the PR event
            #   run: echo "${{ github.event.pull_request.title }}"
            # - name: Print PR labels
            #   run: |
            #     cat << EOF
            #         ${{ toJson(github.event.pull_request.labels) }}
            #         EOF
            # - name: Bug step
            #   if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
            #   run: echo "I am a bug fix"
            - name: Sleep 20 sec
              run: sleep 20   
            - name: Failing step
              run: |
                echo "I will fail"
                exit 1
            - name: Skipped step
              if: ${{ success() }}
              run: echo "I will run if previous steps succeed."
            - name: Execute step
              if: ${{ failure() }}
              run: echo "I will print if any previous step fails."
            - name: I will Execute
              if: ${{ !cancelled() }}
              run: echo "I will always print, except when the workflow is cancelled."
            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "I will print when the workflow is cancelled"